name: My first workflow
on: push # it can be multiple options [push, pull]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Welcome Message
        run: |
          echo "My first GitHub Actions Job"
          ls
          cat README.md

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for Cover, I am a Dragon." >> dragon.txt

      - name: Printing the dragon.txt file content
        run: cat dragon.txt

      - name: Run Bash Script
        run: |
          sudo chmod +x ascii-script.sh
          ./ascii-script.sh